name: Maven Github Action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run test for maven
    runs-on: ubuntu-latest
    steps:
      - name: get the source code
        uses: actions/checkout@v6
      - name: set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: running test
        run: mvn test
  build:
    needs: test
    outputs:
      artifact_data: ${{ steps.artifact-name.outputs.artifact_data }}
    name: Run build for maven
    runs-on: ubuntu-latest
    steps:
      - name: get the source code
        uses: actions/checkout@v6
      - name: set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: building jar file
        run: mvn clean package
      - name: upload jar file
        uses: actions/upload-artifact@v6
        with:
          name: artifact-data
          path: target/*.jar
      - name: get the artifact name
        id: artifact-name
        run: find target/*.jar -type f -execdir echo 'artifact_data={}' >> $GITHUB_OUTPUT ';'
  deploy:
      needs: build
      name: take the artifact
      runs-on: ubuntu-latest
      steps:
        - name: taking artifacts from build job
          uses: actions/download-artifact@v7
          with:
            name: artifact-data
        - name: list my artifacts
          run: ls
        - name: getting arifact file name
          run: echo ${{needs.build.outputs.artifact_data}}



