name: Maven Github Action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Run test for maven
    runs-on: ubuntu-latest
    steps:
      - name: get the source code
        uses: actions/checkout@v6
      - name: set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: running test
        run: mvn test
  build:
    needs: test
    name: Run build for maven
    runs-on: ubuntu-latest
    steps:
      - name: get the source code
        uses: actions/checkout@v6
      - name: set up java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: building jar file
        run: mvn clean package

